Add main database endpoints
ELTE-Clean/Clean-Administration-Platform pull request #55
Opened 2022-04-08 12:11 UTC by the4t4

Added the following endpoints:

- [GET] /section/all
- [POST] /section/add
- [GET] api/section/tasks/all
- [PUT] api/section/edit
- [PUT] api/task/edit
- [PUT] api/student/add
- [PUT] api/group/assign

None of them have been tested yet because the frontend is failing the application.
The database has been updated, but not yet completely to match the requirements of #52

2022-04-08 12:15 UTC, the4t4 commented
@Abdulla-Alkhulaqui the frontend is failing to build with this error:

#9 45.62 npm ERR! code EBADPLATFORM
#9 45.64 npm ERR! notsup Unsupported platform for @next/swc-win32-ia32-msvc@12.0.10: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
#9 45.64 npm ERR! notsup Valid OS:    win32
#9 45.64 npm ERR! notsup Valid Arch:  ia32
#9 45.64 npm ERR! notsup Actual OS:   linux
#9 45.64 npm ERR! notsup Actual Arch: x64

Do you have any idea what this is?

2022-04-08 12:53 UTC, Mohido commented
@the4t4  Just three main things to point out: 
1) The first one is we still need the exports for all the utils functions since the backend can utilize whatever it needs from this database_utils.ts.
2) The call of a promised function in the utility requires the `await` keyword before it since they return promises. Promises can be thought of as individual threads. The behavior of the database endpoints that you defined is unpredictable.  So for instance, in `insertIntoTable('section', req.body);` and the line underneath it: `res.status(200).send(JSON.stringify({message: "New section added"}));`. This will return status 200 no matter if the insertIntoTable() is valid or not. The paradigm I use is that I always return a result (QryResult) that has the result or the error. 
3) In the future, there must be validation layers such that a demonstrator, only, can add a section to his assigned group and no other group.  However, the current `getUserKeycloak` is not returning the roles. Therefore, I skipped that part. However, if you want to make sure that this is almost complete, you need to add at least a validation layer that the user (no matter the role for now) can alter only his specified groups/sections/tasks.

2022-04-08 12:55 UTC, Mohido commented on backend/routes/main.js
> +    const result = selectFromTable('section');
async (req,res,next) => {
const result = await selec...
}

2022-04-08 13:03 UTC, Mohido requested changes
The main changes that must be done is the async/await for the async function calls.

2022-04-08 13:03 UTC, Mohido commented on backend/utils/database_utils.ts
> +    endTrans(transInstance);
await must be for endTrans() as I recall as well.

2022-04-08 13:03 UTC, Mohido commented on backend/utils/database_utils.ts
> +interface QryResult {
we need all the utilities to be exported.

2022-04-08 13:03 UTC, Mohido commented on backend/routes/users.js
> +    const userReqDB = selectFromTable('users', {username : userReqKC.user.username})
add await for async calls

2022-04-08 13:03 UTC, Mohido commented on backend/routes/main.js
> + router.delete("/group/unassign", (req, res, next) => {
async (req, res, next) => {
 await ...
 return..
 }

2022-04-08 13:11 UTC, the4t4 commented on backend/utils/database_utils.ts
> +    endTrans(transInstance);
Why? Is it important for us to wait for it to end? I get that it might fail to end but so what? how are we going to handle it if we decide to catch the error?

2022-04-08 13:13 UTC, the4t4 commented on backend/utils/database_utils.ts
> +interface QryResult {
Sure, but I don't see it being used anywhere

2022-04-08 13:17 UTC, the4t4 commented on backend/routes/users.js
> +    const userReqDB = selectFromTable('users', {username : userReqKC.user.username})
Done

2022-04-08 13:18 UTC, the4t4 commented on backend/routes/main.js
> + router.delete("/group/unassign", (req, res, next) => {
Same question as above

2022-04-08 13:29 UTC, the4t4 commented
@Mohido 

1. I exported them again but I don't see the point since we added the layer of abstraction. I don't see any use case for execQry execTrans etc because now we have a better method for them which handles everything.
2. Yeah I missed to put await/async calls to for the select statements but for the others, it will return 200 no matter what as I have pointed out in my [other PR](https://github.com/ELTE-Clean/Clean-Administration-Platform/pull/48).
3. I have left the validation out because these endpoints aren't even tested yet.

2022-04-08 13:37 UTC, Mohido commented
@the4t4 
1) The most useful use-case would be if we need to implement some other utility that relies on this utility to function. That utility will be in TS since its the standard for implementing our utilities (more robust). Other things are minor use-cases. However, for me I would love to export everything in the utilities to the backend and the backend developer can deal with it (Unless it is a secret configuration maybe?) . Having this standardized help the other developers that will come after us.

2) Yes you are correct regarding that one. It will always return 200. Not a big deal for now, since the front-end was off for testing

3) Gotcha mate

2022-04-08 13:39 UTC, Mohido commented on backend/utils/database_utils.ts
> +interface QryResult {
TypeScript utilities would need to access that since they are strict about what variables do objects have :)

2022-04-08 13:41 UTC, Mohido commented on backend/utils/database_utils.ts
> +    endTrans(transInstance);
If we decide to catch the error we can return a different status. In the endTrans, if an error occurs, it will rollback the whole transaction as I recall. Therefore, we need to inform the user maybe or do some other stuff with the error or the result.

2022-04-21 09:35 UTC, the4t4 commented
@Mohido ready for review

2022-04-21 13:37 UTC, Mohido approved these changes
Everything seems alright, just the endpoints distribution can be improved. Other than that all seems legit.

2022-04-21 13:44 UTC, merged