Connected admin endpoints
ELTE-Clean/Clean-Administration-Platform pull request #77
Opened 2022-05-27 14:39 UTC by RealGorandos

Connected create/delete user and create group endpoints....(add/remove user to a group needs to change the passed body in the frontend)

2022-05-28 09:56 UTC, Abdulla-Alkhulaqui approved these changes

2022-05-28 09:57 UTC, Abdulla-Alkhulaqui commented
@Mohido  there are some changes in the backend in this PR, please review them.

2022-05-28 15:05 UTC, Mohido commented on backend/routes/sections.js
> +    for (const section of req.body) {
Not approved

2022-05-28 15:05 UTC, Mohido commented on backend/routes/tasks.js
> +    if(req.query.groupid)
We don't have groupids in the get tasks.

2022-05-28 15:06 UTC, Mohido commented on backend/routes/tasks.js
> +            groupid : task.groupID,
Missing data and groupid is not a column in the tables

2022-05-28 15:07 UTC, Mohido commented on backend/routes/tasks.js
> +    // if(incompleteFile || incompleteBody)
This is not the latest tasks endpoint. Please rebase before pushing

2022-05-28 15:08 UTC, Mohido commented on backend/routes/users.js
> +            neptun: user.username
Redundent

2022-05-28 15:09 UTC, Mohido requested changes
Please, return the backend to the latest push. This version is old and edited. The new editions are not compatible.

2022-06-04 01:55 UTC, RealGorandos commented
@Abdulla-Alkhulaqui  Please check the frontend after the rebase.
@Mohido  @the4t4  I have rebased the BE of this branch to development please check those files!

2022-06-04 09:34 UTC, Mohido approved these changes
Backend looks fine.

2022-06-04 12:09 UTC, the4t4 approved these changes

2022-06-10 16:42 UTC, Abdulla-Alkhulaqui commented
> @RealGorandos Merge?

I will after merging mine.

2022-06-10 17:09 UTC, the4t4 commented
Pls squash merge merge lol, 91 commits and counting

2022-06-10 17:17 UTC, RealGorandos commented
@Abdulla-Alkhulaqui How about merging those two then urs :)

2022-06-11 15:26 UTC, merged